### ISSUE TITLE
TLS is not detected when running behind a reverse proxy

### ISSUE THREAD

**Issue by yanosz** [julianxhokaxhiu/LineageOTA#51] opened 2019-06-04 08:55 UTC
Is:
 * index.php has
```php   
   if( isset($_SERVER['HTTPS'] ) )
        $protocol = 'https://';
    else
        $protocol = 'http://';`
```
This fails to detect reverse-proxy situations (c.f. https://bugs.php.net/bug.php?id=66398)

Shoud:
* index.php schould honor `X-FORWARDED-PROTO`

**Comment by julianxhokaxhiu** [comment] 2019-06-04 21:50
I'll check how to patch it later this week, but if you can come with a PR I would be more than fine in reviewing it. Thank you in advance!

**Comment by yanosz** [comment] 2019-06-11 13:24
thank's well, I'm not an expert in php, so i manually patched https to be always on ... that won't make it a good pr... other attemptes failed :-/

**Comment by reknitse** [comment] 2019-09-11 08:24
I would suggest to change 
`if( isset($_SERVER['HTTPS'] ) )`
to 
`if( isset($_SERVER['HTTPS'] ) || $_ENV["USE_HTTPS"] )`
This way everyone with reverse proxy can fix this via an environment variable $USE_HTTPS.

**Comment by julianxhokaxhiu** [comment] 2019-09-12 09:46
I'll try to work on this within the next days. I'll post here as soon as it is done.

**Comment by julianxhokaxhiu** [comment] 2019-10-30 16:12
Can you please try now if it works fine @yanosz ?

**Comment by TpmKranz** [comment] 2019-10-30 16:14
Don't forget to set the `Forwarded:` header as mentioned in #55.

**Comment by yanosz** [comment] 2019-11-02 18:17
Thanks for your feedback - unfornutaly, I gave up building lineageos a few months ago - sec fixes were no longer ported to 14.1 - thus there was no point in setting up a build system anymore. :-/

**Comment by TpmKranz** [comment] 2019-11-02 19:55
Sorry to hear that. Security patches for 14.1 were the only reason for my build system as well. Are you sure? I've just recently built LOS 14.1 and the security patch level said “5 October 2019”.

**Comment by yanosz** [comment] 2019-11-06 09:04
Not 100% sure about that - my Moto G4 was stuck at April 2019 for a few months, than I gave up using that phone. But that's OT, IMHO

**Comment by newhinton** [comment] 2020-02-07 13:28
@TpmKranz Could you tell me how this would work with apache? 

`RequestHeader set X-Forwarded-proto "https"`
or similar does not work for me

Edit:

if i set `$_SERVER['HTTP_FORWARDED'] = "HOST=x/los/;PROTO=https";`
it seems to set all proper values througout the index.php, however, the url provided for the update.zip-files are not using them.

**Comment by ionphractal** [comment] 2020-03-29 17:57
@julianxhokaxhiu @TpmKranz Just tried the latest docker image and https detection didn't work. I'm using caddy in front and I have confirmed via tcpdump that the X-Forwarded-Proto header is set correctly. I hardly have experience with PHP but from the official documentation I could not find where you got the $_SERVER['HTTP_FORWARDED'] variable from. And when I print $_SERVER in index.php into a file, it does not contain HTTP_FORWARDED, only the HTTP_X_* variables. Is it something proxy specific (e.g. nginx)? Then I would rather suggest using the standard approach with the X headers.

Replacing 

https://github.com/julianxhokaxhiu/LineageOTA/blob/2.0/index.php#L29-L43 

with
```
    if ( isset($_SERVER['HTTP_X_FORWARDED_HOST']) ) {
      $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
    }
    if ( isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtoupper($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'HTTPS' ) {
      $_SERVER['HTTPS'] = 'on';
    }
```
does the trick for me. Though, I actually don't use the HTTP_X_FORWARDED_HOST header but I kept it for completeness.

**Comment by TpmKranz** [comment] 2020-03-29 18:05
As mentioned in #55, my implementation follows [RFC 7239](https://tools.ietf.org/html/rfc7239), which aims to deprecate the decidedly non-standard `X-` headers.

**Comment by julianxhokaxhiu** [comment] 2020-03-29 18:21
I'd be more than happy to evaluate a PR as I do not have the time at this very moment to work on it actively. Thank you in advance for the effort being put on this.

**Comment by ionphractal** [comment] 2020-03-29 19:09
@TpmKranz not sure why you think it X headers are deprecated https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded .
> The alternative and de-facto standard versions of this header are the X-Forwarded-For, X-Forwarded-Host and X-Forwarded-Proto headers.

Anyway, I don't think it can hurt to support both.

@julianxhokaxhiu Created a new PR https://github.com/julianxhokaxhiu/LineageOTA/pull/57

**Comment by julianxhokaxhiu** [comment] 2020-03-29 19:17
PR merged. Feel free to try and let me know!

**Comment by ionphractal** [comment] 2020-03-29 19:31
Works for me, thank you! Can someone with an appropriate setup please test the forwarded headers?

**Comment by TpmKranz** [comment] 2020-03-30 10:04
@ionphractal I didn't say that the `X-` headers were deprecated; just that the RFC aims to deprecate them (by proposing a standardized alternative). I simply preferred to implement that RFC instead of the `X-` headers and didn't mean to disrespect, if that's the message you got. :)

**Comment by ionphractal** [comment] 2020-03-30 16:31
@TpmKranz No worries, didn't get it like that :) And I didn't want to be disrespectful either. From operator perspective the `X-` headers were natural to me and seem to be more common. But both need to be supported to avoid issues. So one part plus another one makes it better ;)

**Comment by julianxhokaxhiu** [comment] 2020-03-30 16:56
Well both are supported now, it would not hurt anyone. Unfortunately Standards are not for everyone and software tend to get complex exactly because of this.

Thanks to @ionphractal for the PR and I'd be happy to close this issue as both methods are in place. Feel free to write back here in case some issues arise.

**Closed as completed by julianxhokaxhiu** 2020-03-30 16:56 UTC
Labels: bug, help-needed
