### ISSUE TITLE
Check if php's zip extension is enabled

### ISSUE THREAD

**Issue by jnsc** [julianxhokaxhiu/LineageOTA#27] opened 2017-05-27 18:57 UTC
Hi, I had quite a hard time to debug my installation, the problem was that the php zip extension was not enabled. Do you think it's possible to check the presence of the zip extension using  if (!extension_loaded('zip')). 

the error is not displayed because file_get_contents is prefixed by a @.

**Comment by julianxhokaxhiu** [comment] 2017-05-27 19:48
The problem is that even if I would add a check, it would be useless, as without the whole OTA server would not work.

**Comment by jnsc** [comment] 2017-05-27 19:56
Yes, of course it's needed, but an error message would help to debug the situation.

**Comment by julianxhokaxhiu** [comment] 2017-06-24 12:25
Shouldn't PHP warn you about this?

**Comment by jnsc** [comment] 2017-06-24 14:15
Yes, but the @ before the line removes the warning.

**Comment by julianxhokaxhiu** [comment] 2017-06-24 22:13
I see. Unfortunately I had to use that signature to purge Warnings too. I have nothing against your suggestion but to be honest, I would just prefer to add a requirements sections in composer.json and/or the README.

I'll see what I can archive from composer.

**Comment by julianxhokaxhiu** [comment] 2017-06-24 22:23
Done. Will be included in the next release.

**Closed as completed** 2017-06-24 22:23 UTC
